SELECT
	    1 AS TABLEID       
	   ,TABLE_NAME
FROM
	INFORMATION_SCHEMA.TABLES
WHERE
	TABLE_TYPE = 'BASE TABLE'
	AND TABLE_NAME != 'dtProperties'
	AND TABLE_CATALOG = '#DatabaseName#'	
    AND TABLE_SCHEMA = 'public' 
ORDER BY TABLE_NAME
