/**********************************************************
  AUTHOR	: #AUTHOR#
  VERSION	: #VERSION#
  DATE		: #DATETIME#
  FUNCTION	: Delete a record in the table #TABLE#
**********************************************************/
--Create the SQL for the stored procedure
IF EXISTS (SELECT * FROM DBO.SYSOBJECTS WHERE ID = OBJECT_ID(N'[dbo].[#TABLEWITHOUTPREFIXTABLE#_Delete]') AND OBJECTPROPERTY(id, N'IsProcedure') = 1)
	DROP PROCEDURE [dbo].[#TABLEWITHOUTPREFIXTABLE#_Delete]
GO

SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE PROCEDURE [dbo].[#TABLEWITHOUTPREFIXTABLE#_Delete]
(
	@#PRIMARYKEY# #TYPEPRIMARYKEYSQLSERVER#
)
AS
BEGIN
	DELETE FROM #TABLE#
	WHERE [#PRIMARYKEY#] = @#PRIMARYKEY#
END
GO

IF EXISTS (SELECT * FROM DBO.SYSOBJECTS WHERE ID = OBJECT_ID(N'[dbo].[#TABLEWITHOUTPREFIXTABLE#_DeleteList]') AND OBJECTPROPERTY(id, N'IsProcedure') = 1)
	DROP PROCEDURE [dbo].[#TABLEWITHOUTPREFIXTABLE#_DeleteList]
GO

SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE PROCEDURE [dbo].[#TABLEWITHOUTPREFIXTABLE#_DeleteList]
(
	 @#PRIMARYKEY# #TYPEPRIMARYKEYSQLSERVER#,
	<allfieldslessprimarykey>
	@#FIELD# #TYPEDBSQLSERVER# = NULL#COMMAAFTER#
	</allfieldslessprimarykey>
)
AS
BEGIN
	DELETE FROM
		#TABLE# 
    WHERE 
		([#PRIMARYKEY#] = @#PRIMARYKEY# OR @#PRIMARYKEY# IS NULL)
		<allfieldslessprimarykey>
	  AND ([#FIELD#] = @#FIELD# OR @#FIELD# IS NULL)
		</allfieldslessprimarykey>       
	 
END
GO


GRANT EXECUTE ON [dbo].[#TABLEWITHOUTPREFIXTABLE#_Delete] TO [#GRANTUSER#]
GO

GRANT VIEW DEFINITION ON [dbo].[#TABLEWITHOUTPREFIXTABLE#_Delete] TO [#GRANTUSER#]
GO
