//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by SHLStudio.rc
//
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDS_SERVEREXPLORER              101
#define IDS_DATA_CONNECTION             102
#define IDR_GUI_DETYPE                  103
#define IDB_WRITESMALL                  110
#define IDB_WRITELARGE                  111
#define IDB_MAIN                        112
#define IDB_BUTTONS                     113
#define IDB_FILELARGE                   114
#define IDB_FILESMALL                   115
#define IDR_POPUP_EDIT                  119
#define ID_STATUSBAR_PANE1              120
#define ID_STATUSBAR_PANE2              121
#define IDS_STATUS_PANE1                122
#define IDS_STATUS_PANE2                123
#define IDR_MAINFRAME                   128
#define IDR_MAINFRAME_256               129
#define IDR_SHLStudioTYPE               130
#define ID_WINDOW_MANAGER               131
#define ID_VIEW_SolutionView            133
#define ID_VIEW_CLASSVIEW               134
#define ID_PROPERTIES                   135
#define ID_OPEN                         136
#define ID_OPEN_WITH                    137
#define ID_DUMMY_COMPILE                138
#define ID_CLASS_ADD_MEMBER_FUNCTION    139
#define ID_CLASS_ADD_MEMBER_VARIABLE    140
#define ID_CLASS_DEFINITION             141
#define ID_CLASS_PROPERTIES             142
#define ID_NEW_FOLDER                   143
#define ID_SORT_MENU                    144
#define ID_SORTING_GROUPBYTYPE          145
#define ID_SORTING_SORTALPHABETIC       146
#define ID_SORTING_SORTBYTYPE           147
#define ID_SORTING_SORTBYACCESS         148
#define ID_VIEW_OUTPUTWND               149
#define ID_VIEW_PROPERTIESWND           150
#define IDR_PASTE_MENU                  151
#define ID_SORTPROPERTIES               151
#define IDR_WINDOWS_MENU                152
#define ID_EXPAND_ALL                   154
#define IDS_FILE_VIEW                   155
#define IDS_CLASS_VIEW                  156
#define IDS_OUTPUT_WND                  157
#define IDS_PROPERTIES_WND              158
#define IDI_FILE_VIEW                   161
#define IDI_FILE_VIEW_HC                162
#define IDI_CLASS_VIEW                  163
#define IDI_CLASS_VIEW_HC               164
#define IDI_OUTPUT_WND                  165
#define IDI_OUTPUT_WND_HC               166
#define IDI_PROPERTIES_WND              167
#define IDI_PROPERTIES_WND_HC           168
#define IDR_EXPLORER                    169
#define IDB_EXPLORER_24                 170
#define IDR_SORT                        171
#define IDB_SORT_24                     172
#define IDR_POPUP_SORT                  173
#define IDR_POPUP_EXPLORER_PROJECT      174
#define IDB_FILE_VIEW                   175
#define IDB_FILE_VIEW_24                176
#define IDB_CLASS_VIEW                  177
#define IDB_CLASS_VIEW_24               178
#define IDR_MENU_IMAGES                 179
#define IDB_MENU_IMAGES_24              180
#define ID_TOOLS_MACRO                  181
#define IDR_OUTPUT_POPUP                182
#define IDR_PROPERTIES                  183
#define IDB_PROPERTIES_HC               184
#define ID_VIEW_NAVIGATION              185
#define IDB_NAVIGATION_LARGE            186
#define IDB_NAVIGATION_LARGE_HC         187
#define IDB_PAGES                       188
#define IDB_PAGES_HC                    189
#define IDB_PAGES_SMALL                 190
#define IDB_PAGES_SMALL_HC              191
#define IDR_THEME_MENU                  200
#define ID_SET_STYLE                    201
#define IDR_POPUP_EXPLORER_ITEM         201
#define IDR_POPUP_EXPLORER_SOLUTION     202
#define IDR_POPUP_EXPLORER_FOLDER       203
#define IDR_POPUP_EXPLORER_DEPENDENCY   204
#define ID_VIEW_APPLOOK_WIN_2000        205
#define ID_VIEW_APPLOOK_OFF_XP          206
#define ID_VIEW_APPLOOK_WIN_XP          207
#define ID_VIEW_APPLOOK_OFF_2003        208
#define ID_VIEW_APPLOOK_VS_2005         209
#define ID_VIEW_APPLOOK_VS_2008         210
#define ID_VIEW_APPLOOK_OFF_2007_BLUE   215
#define ID_VIEW_APPLOOK_OFF_2007_BLACK  216
#define ID_VIEW_APPLOOK_OFF_2007_SILVER 217
#define ID_VIEW_APPLOOK_OFF_2007_AQUA   218
#define ID_VIEW_APPLOOK_WINDOWS_7       219
#define ID_TOOLS_OPTIONS                220
#define ID_VIEW_CAPTION_BAR             221
#define ID_PROPERTY_COMBO               222
#define ID_PROPERTY_LIST                223
#define IDB_INFO                        230
#define IDS_CAPTION_BUTTON              231
#define IDS_CAPTION_BUTTON_TIP          232
#define IDS_CAPTION_TEXT                233
#define IDS_CAPTION_IMAGE_TIP           234
#define IDS_CAPTION_IMAGE_TEXT          235
#define IDS_MYCALENDARS                 250
#define IDS_CALENDAR                    251
#define IDS_SHORTCUTS                   252
#define IDS_FOLDERS                     253
#define IDS_OUTLOOKBAR                  258
#define IDS_BUILD_TAB                   300
#define IDS_DEBUG_TAB                   301
#define IDS_FIND_TAB                    302
#define IDS_EXPLORER                    305
#define IDS_EDIT_MENU                   306
#define IDR_RIBBON                      307
#define IDD_DIALOG_NEW_PROJECT_AND_FILE 310
#define IDD_TREE_VIEW                   310
#define ID_TREE_VIEW_TAB_SOLUTION       311
#define ID_TREE_VIEW_TAB_PROJECT        312
#define ID_TREE_VIEW_TAB_FOLDER         313
#define ID_TREE_VIEW_TAB_ITEM           314
#define IDB_SHL_COLLAPSE_ARROW          314
#define IDB_SHL_EXPAND_ARROW            315
#define ID_TREE_VIEW_TAB_DEPENDENCY     315
#define IDB_SOLUTION_EXPLORER           316
#define IDR_TOOLBAR_SERVER_EXPLORER     316
#define ID_VIEW_SERVER_EXPLOERE         317
#define IDB_DATA_ADD                    318
#define IDB_DATA_CONNECTIONS            319
#define IDB_DATA_DELETE                 320
#define IDB_DATA_SAVE                   321
#define IDR_DATA_CONNECTION             323
#define IDR_DATA_CONNECTION_NULL        324
#define IDR_DATA_CONNECTION_QUERY       325
#define IDB_DATA_BASE                   325
#define IDB_DATA_CONNECTION_ON          327
#define IDB_DATA_TABLE                  328
#define IDB_DATA_COLUMN                 329
#define IDB_DATA_FOLDER                 330
#define IDB_DATA_CONNECTION             331
#define IDB_DATA_PROGRAMATICALLY        332
#define IDB_DATA_KEY                    333
#define IDB_DATA_CONSTRAINT             334
#define IDB_DATA_INDEX                  335
#define IDB_DATA_TRIGGER                336
#define IDB_DATA_SEQUENCE               337
#define IDB_DATA_CONNECTION_ADD         338
#define IDB_DATA_CONNECTION_SAVE        339
#define IDB_TOOLBAR_SQL_LARGE           345
#define IDB_TOOLBAR_SQL_SMALL           346
#define IDR_SERVER_EXPLORER             347
#define IDB_DATA_REFRESH_16             349
#define IDB_DATA_CONNECTION_16          350
#define IDB_DATA_DELETE_16              351
#define IDD_DIALOG_CONFIGURATION_MANAGER 352
#define IDC_TREE_GROUP_PROJECT_FILE     1000
#define IDC_STATIC_NAME                 1001
#define IDC_STATIC_LOCATION             1002
#define IDC_TREE_PROJECT_FILE           1004
#define IDC_EDIT_DESCRIPTION            1005
#define IDC_EDIT_NAME                   1006
#define IDC_EDIT_LOCATION               1007
#define IDC_BUTTON_BROWSER_LOCATION     1008
#define IDC_TREE3                       1017
#define IDC_SPIN1                       1018
#define IDC_LIST_PROJECT_FILE           1019
#define IDC_COMBO1                      1020
#define IDC_COMBO_CATEGORY              1020
#define IDC_GRIDPLACEHOLDER             1021
#define ID_WRITE_PASTEASHYPERLINK       32770
#define ID_EXPLORER_ADD                 32771
#define ID_EXPLORER_ADDFOLDER           32772
#define ID_EXPLORER_RENAME              32773
#define ID_EXPLORER_OPENFOLDERINFILEEXPLORER 32774
#define ID_EXPLORER_VIEWCODE            32775
#define ID_EXPLORER_BUILD               32776
#define ID_EXPLORER_REBUILD             32777
#define ID_EXPLORER_CONFIGURATIONMANAGER 32778
#define ID_EXPLORER_COMPILE             32782
#define ID_DATACONNECTION_ADDNEWCONNECTION 32783
#define ID_DATACONNECTION_REMOVECONNECTION 32784
#define ID_DATACONNECTION_SAVECONNECTIONS 32785
#define ID_DATACONNECTION_PROPERTIES    32786
#define ID_DATACONNECTION_NULL_ADDNEWCONNECTION 32788
#define ID_DATACONNECTION_NEWQUERY      32789
#define ID_DATACONNECTION_REFRESH       32790
#define ID_DATACONNECTION_CONNECT       32792
#define ID_DATACONNECTION_DISCONNECT    32793
#define ID_BUTTON_CONNECTIONS_NEW       32800
#define ID_BUTTON_CONNECTIONS_SAVE      32801
#define ID_BUTTON_DATABASE_CONNECT      32802
#define ID_BUTTON_DATABASE_DISCONNECT   32803
#define ID_COMBO_SQL_DATABASES          32804
#define ID_BUTTON_SQL_EXECUTE           32805
#define ID_BUTTON_SQL_STOP              32806
#define ID_BUTTON_RESULT_GRID           32807
#define ID_BUTTON_RESULT_TEXT           32808
#define ID_BUTTON_NEW_QUERY             32810
#define ID_CHECK_KEEP_TAB_RESULT        32811
#define ID_CHECK_DDL_IN_TEXT_RESULT     32812
#define ID_EXPLORER_GENERATE            32813
#define ID_BUTTON_DATABASE_RECONNECT    32814
#define ID_BUTTON_NEW_SOLUTION          32818
#define ID_BUTTON_OPEN_SCRIPT_FILE      32820
#define ID_BUTTON_OPEN_SOLUTION         32821
#define ID_EDIT_CLOSE                   32822
#define ID_EXPLORER_REMOVE              32823
#define ID_EXPLORER_CLOSE               32824
#define ID_VIEW_BUTTON_SOLUTION_EXPLORER 32828
#define ID_VIEW_BUTTON_SERVER_EXPLORER  32829
#define ID_VIEW_BUTTON_OUTPUT           32830
#define ID_VIEW_BUTTON_PROPERTIES       32831
#define ID_DATACONNECTION_CONNECT_SERVER_EXPLORER_TOOLBAR 32832
#define ID_DATACONNECTION_DISCONNECT_SERVER_EXPLORER_TOOLBAR 32833
#define ID_DATACONNECTION_REFRESH_SERVER_EXPLORER_TOOLBAR 32834
#define ID_ADD_ADDNEWITEM               32834
#define ID_ADD_ADDEXISTINGITEM          32835
#define ID_ADD_NEWITEM                  32836
#define ID_ADD_EXISTINGITEM             32837
#define ID_ADD_NEWITEM32838             32838
#define ID_ADD_EXISTINGPROJECT          32839
#define ID_DATACONNECTION_RENAME        32840
#define ID_DATACONNECTION_RENAME32841   32841

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        353
#define _APS_NEXT_COMMAND_VALUE         32842
#define _APS_NEXT_CONTROL_VALUE         1022
#define _APS_NEXT_SYMED_VALUE           318
#endif
#endif
