/* ***************************************************************************
 * Arquivo: SHLDataConnection.h                                              *
 *                                                                           *
 * Enumerações para o treeview de gerenciamento de conexões para o           *
 * Query Analyzer do SHLStudio.                                              *
 *                                                                           *
 * Data:28/05/2013                                                           *
 * Auto: José Sahle Netto                                                    *
 *************************************************************************** */

#pragma once

#ifndef __SHLDATACONNECTION
#define __SHLDATACONNECTION
#define IMAGE_DATA_CONNECTIONS		0
#define IMAGE_DATA_ADD				1
#define IMAGE_DATA_DELETE			2
#define IMAGE_DATA_SAVE				3
#define IMAGE_DATA_CONNECTION		4
#define IMAGE_DATA_CONNECTION_ON	5
#define IMAGE_DATA_TABLE			6
#define IMAGE_DATA_COLUMN			7
#define IMAGE_DATA_FOLDER			8
#define IMAGE_DATA_BASE				9
#define IMAGE_DATA_PROGRAMATICALLY	10
#define IMAGE_DATA_KEY				11
#define IMAGE_DATA_CONSTRAINT		12
#define IMAGE_DATA_INDEX			13
#define IMAGE_DATA_TRIGGER			14
#define IMAGE_DATA_SEQUENCE			15

typedef enum _shldataconnection
{
	 SHLDATACONNECTION_ID_TREE_DATA_NO_INFORMATION

	,SHLDATACONNECTION_ID_TREE_DATA_CONNECTION

	,SHLDATACONNECTION_ID_TREE_DATA_DATABASE_CONNECTION		

	,SHLDATACONNECTION_ID_TREE_DATA_SYSTEM_TABLE_FOLDER
	,SHLDATACONNECTION_ID_TREE_DATA_SYSTEM_COLUMN_FOLDER
	,SHLDATACONNECTION_ID_TREE_DATA_SYSTEM_VIEW_FOLDER
	,SHLDATACONNECTION_ID_TREE_DATA_SYSTEM_SEQUENCE_FOLDER
	,SHLDATACONNECTION_ID_TREE_DATA_SYSTEM_CONSTRAINT_FOLDER
	,SHLDATACONNECTION_ID_TREE_DATA_SYSTEM_TRIGGER_FOLDER
	,SHLDATACONNECTION_ID_TREE_DATA_SYSTEM_INDEX_FOLDER
	,SHLDATACONNECTION_ID_TREE_DATA_SYSTEM_PROCEDURE_FOLDER			
	,SHLDATACONNECTION_ID_TREE_DATA_SYSTEM_FUNCTION_FOLDER			

	,SHLDATACONNECTION_ID_TREE_DATA_USER_TABLE_FOLDER
	,SHLDATACONNECTION_ID_TREE_DATA_USER_COLUMN_FOLDER
	,SHLDATACONNECTION_ID_TREE_DATA_USER_VIEW_FOLDER
	,SHLDATACONNECTION_ID_TREE_DATA_USER_SEQUENCE_FOLDER
	,SHLDATACONNECTION_ID_TREE_DATA_USER_CONSTRAINT_FOLDER
	,SHLDATACONNECTION_ID_TREE_DATA_USER_TRIGGER_FOLDER
	,SHLDATACONNECTION_ID_TREE_DATA_USER_INDEX_FOLDER
	,SHLDATACONNECTION_ID_TREE_DATA_USER_PROCEDURE_FOLDER			
	,SHLDATACONNECTION_ID_TREE_DATA_USER_FUNCTION_FOLDER			

	/* ********************** SYSTEM ****************************** */
	// DATABASE
	,SHLDATACONNECTION_ID_TREE_DATA_SYSTEM_DATABASES					
	,SHLDATACONNECTION_ID_TREE_DATA_SYSTEM_DATABASE_NAME				

	//TABLES & COLUMNS & KEYS & TIGGERS & INDEXES & SEQUENCES 
	,SHLDATACONNECTION_ID_TREE_DATA_SYSTEM_TABLE					
	,SHLDATACONNECTION_ID_TREE_DATA_SYSTEM_TABLE_COLUMNS				
	,SHLDATACONNECTION_ID_TREE_DATA_SYSTEM_TABLE_COLUMN_DETAIL		
	,SHLDATACONNECTION_ID_TREE_DATA_SYSTEM_TABLE_KEYS					
	,SHLDATACONNECTION_ID_TREE_DATA_SYSTEM_TABLE_KEY_DETAIL			
	,SHLDATACONNECTION_ID_TREE_DATA_SYSTEM_TABLE_CONSTRAINTS			
	,SHLDATACONNECTION_ID_TREE_DATA_SYSTEM_TABLE_CONSTRAINTS_DETAIL
	,SHLDATACONNECTION_ID_TREE_DATA_SYSTEM_TABLE_TRIGGERS				
	,SHLDATACONNECTION_ID_TREE_DATA_SYSTEM_TABLE_TRIGGERS_DETAIL		
	,SHLDATACONNECTION_ID_TREE_DATA_SYSTEM_TABLE_INDEXES				
	,SHLDATACONNECTION_ID_TREE_DATA_SYSTEM_TABLE_INDEX_DETAIL			
	,SHLDATACONNECTION_ID_TREE_DATA_SYSTEM_TABLE_SEQUENCES			
	,SHLDATACONNECTION_ID_TREE_DATA_SYSTEM_TABLE_SEQUENCES_DETAIL		

	// VIEW
	,SHLDATACONNECTION_ID_TREE_DATA_SYSTEM_VIEW				
	,SHLDATACONNECTION_ID_TREE_DATA_SYSTEM_VIEW_PARAMETERS			
	,SHLDATACONNECTION_ID_TREE_DATA_SYSTEM_VIEW_COLUMN_DETAIL			

	// PROCEDURE
	,SHLDATACONNECTION_ID_TREE_DATA_SYSTEM_PROCEDURE
	,SHLDATACONNECTION_ID_TREE_DATA_SYSTEM_PROCEDURE_PARAMETERS		
	,SHLDATACONNECTION_ID_TREE_DATA_SYSTEM_PROCEDURE_COLUMN_DETAIL	

	// FUNCTON
	,SHLDATACONNECTION_ID_TREE_DATA_SYSTEM_FUNCTION			
	,SHLDATACONNECTION_ID_TREE_DATA_SYSTEM_FUNCTION_PARAMETERS		
	,SHLDATACONNECTION_ID_TREE_DATA_SYSTEM_FUNCTION_COLUMN_DETAIL	

	/* ********************** USER ****************************** */
	// DATABASE
	,SHLDATACONNECTION_ID_TREE_DATA_USER_DATABASES					
	,SHLDATACONNECTION_ID_TREE_DATA_USER_DATABASE_NAME				

	//TABLES & COLUMNS & KEYS & TIGGERS & INDEXES & SEQUENCES - USER
	,SHLDATACONNECTION_ID_TREE_DATA_USER_TABLE					
	,SHLDATACONNECTION_ID_TREE_DATA_USER_TABLE_COLUMNS				
	,SHLDATACONNECTION_ID_TREE_DATA_USER_TABLE_COLUMN_DETAIL		
	,SHLDATACONNECTION_ID_TREE_DATA_USER_TABLE_KEYS					
	,SHLDATACONNECTION_ID_TREE_DATA_USER_TABLE_KEY_DETAIL			
	,SHLDATACONNECTION_ID_TREE_DATA_USER_TABLE_CONSTRAINTS			
	,SHLDATACONNECTION_ID_TREE_DATA_USER_TABLE_CONSTRAINTS_DETAIL
	,SHLDATACONNECTION_ID_TREE_DATA_USER_TABLE_TRIGGERS				
	,SHLDATACONNECTION_ID_TREE_DATA_USER_TABLE_TRIGGERS_DETAIL		
	,SHLDATACONNECTION_ID_TREE_DATA_USER_TABLE_INDEXES				
	,SHLDATACONNECTION_ID_TREE_DATA_USER_TABLE_INDEX_DETAIL			
	,SHLDATACONNECTION_ID_TREE_DATA_USER_TABLE_SEQUENCES			
	,SHLDATACONNECTION_ID_TREE_DATA_USER_TABLE_SEQUENCES_DETAIL		

	// VIEW
	,SHLDATACONNECTION_ID_TREE_DATA_USER_VIEW					
	,SHLDATACONNECTION_ID_TREE_DATA_USER_VIEW_PARAMETERS			
	,SHLDATACONNECTION_ID_TREE_DATA_USER_VIEW_COLUMN_DETAIL			

	// PROCEDURE
	,SHLDATACONNECTION_ID_TREE_DATA_USER_PROCEDURE				
	,SHLDATACONNECTION_ID_TREE_DATA_USER_PROCEDURE_PARAMETERS		
	,SHLDATACONNECTION_ID_TREE_DATA_USER_PROCEDURE_COLUMN_DETAIL	

	// FUNCTION
	,SHLDATACONNECTION_ID_TREE_DATA_USER_FUNCTION				
	,SHLDATACONNECTION_ID_TREE_DATA_USER_FUNCTION_PARAMETERS		
	,SHLDATACONNECTION_ID_TREE_DATA_USER_FUNCTION_COLUMN_DETAIL	
}SHLDATACONNECTION;
#endif